const CLOUDINARY_BASE_URL = process.env.NEXT_PUBLIC_CLOUDINARY_API_BASE_URL;
const CLOUDINARY_VERSION = process.env.NEXT_PUBLIC_CLOUDINARY_API_VERSION;
const CLOUDINARY_CLOUD_NAME = process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME!;
const CLOUDINARY_UPLOAD_PRESET =
  process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET!;
const CLOUDINARY_URL = `${CLOUDINARY_BASE_URL}/${CLOUDINARY_VERSION}/${CLOUDINARY_CLOUD_NAME}/video/upload`;

export const CLOUDINARY_CONFIG = {
  base: CLOUDINARY_BASE_URL,
  version: CLOUDINARY_VERSION,
  name: CLOUDINARY_CLOUD_NAME,
  uploadPreset: CLOUDINARY_UPLOAD_PRESET,
  uploadUrl: CLOUDINARY_URL,
};
